#!/usr/bin/env python3

"""Add offline GeoIP coordinates and ASN data to a Smartnode JSON report.

This utility reads a report generated by ``yerbas-smartnode-check.py``, looks up
public IP addresses using local MaxMind-compatible MMDB files, and replaces the
report atomically. No Smartnode IP address is sent to an external service.
"""

from __future__ import annotations

import argparse
import ipaddress
import json
import os
import sys
import tempfile
from pathlib import Path
from typing import Any


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Enrich a Yerbas Smartnode JSON report with country, city, "
            "latitude, longitude, ASN, and provider data."
        )
    )
    parser.add_argument(
        "--json",
        type=Path,
        required=True,
        help="Smartnode JSON report to update",
    )
    parser.add_argument(
        "--geoip-city-db",
        type=Path,
        required=True,
        help="Path to GeoLite2-City.mmdb or another compatible City database",
    )
    parser.add_argument(
        "--geoip-asn-db",
        type=Path,
        help="Optional path to GeoLite2-ASN.mmdb or another compatible ASN database",
    )
    parser.add_argument(
        "--output",
        type=Path,
        help="Write to a different file instead of replacing --json",
    )
    return parser.parse_args()


def load_geoip_module() -> Any:
    try:
        import geoip2.database  # type: ignore
    except ImportError as exc:
        raise RuntimeError(
            "The geoip2 package is not installed. Run: python3 -m pip install geoip2"
        ) from exc

    return geoip2.database


def load_report(path: Path) -> dict[str, Any]:
    try:
        report = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise RuntimeError(f"Report not found: {path}") from exc
    except json.JSONDecodeError as exc:
        raise RuntimeError(f"Report is not valid JSON: {path}: {exc}") from exc
    except OSError as exc:
        raise RuntimeError(f"Unable to read report {path}: {exc}") from exc

    if not isinstance(report, dict):
        raise RuntimeError("Report root must be a JSON object")

    smartnodes = report.get("smartnodes")
    if not isinstance(smartnodes, list):
        raise RuntimeError("Report does not contain a smartnodes array")

    return report


def lookup_city(reader: Any, ip: str) -> dict[str, Any]:
    result: dict[str, Any] = {
        "country": "",
        "country_code": "",
        "city": "",
        "latitude": None,
        "longitude": None,
        "accuracy_radius_km": None,
        "time_zone": "",
    }

    if reader is None:
        return result

    try:
        record = reader.city(ip)
    except Exception:
        return result

    result["country"] = record.country.name or ""
    result["country_code"] = record.country.iso_code or ""
    result["city"] = record.city.name or ""
    result["latitude"] = record.location.latitude
    result["longitude"] = record.location.longitude
    result["accuracy_radius_km"] = record.location.accuracy_radius
    result["time_zone"] = record.location.time_zone or ""
    return result


def lookup_asn(reader: Any, ip: str) -> dict[str, Any]:
    result: dict[str, Any] = {
        "asn": None,
        "organization": "",
    }

    if reader is None:
        return result

    try:
        record = reader.asn(ip)
    except Exception:
        return result

    result["asn"] = record.autonomous_system_number
    result["organization"] = record.autonomous_system_organization or ""
    return result


def write_json_atomically(report: dict[str, Any], destination: Path) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)

    file_descriptor, temporary_name = tempfile.mkstemp(
        prefix=destination.name + ".",
        suffix=".tmp",
        dir=str(destination.parent),
    )
    temporary_path = Path(temporary_name)

    try:
        with os.fdopen(file_descriptor, "w", encoding="utf-8") as output:
            json.dump(report, output, indent=2, ensure_ascii=False)
            output.write("\n")
            output.flush()
            os.fsync(output.fileno())

        os.replace(temporary_path, destination)
    except Exception:
        try:
            temporary_path.unlink(missing_ok=True)
        except OSError:
            pass
        raise


def main() -> int:
    arguments = parse_arguments()

    if not arguments.geoip_city_db.is_file():
        print(
            f"Error: GeoIP City database not found: {arguments.geoip_city_db}",
            file=sys.stderr,
        )
        return 2

    if arguments.geoip_asn_db and not arguments.geoip_asn_db.is_file():
        print(
            f"Error: GeoIP ASN database not found: {arguments.geoip_asn_db}",
            file=sys.stderr,
        )
        return 2

    try:
        geoip_database = load_geoip_module()
        report = load_report(arguments.json)
    except RuntimeError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 2

    city_reader = None
    asn_reader = None

    try:
        city_reader = geoip_database.Reader(str(arguments.geoip_city_db))
        if arguments.geoip_asn_db:
            asn_reader = geoip_database.Reader(str(arguments.geoip_asn_db))

        cache: dict[str, dict[str, Any]] = {}
        geolocated = 0
        failed = 0
        skipped = 0
        country_codes: set[str] = set()

        for smartnode in report["smartnodes"]:
            if not isinstance(smartnode, dict):
                skipped += 1
                continue

            ip_text = str(smartnode.get("ip") or "").strip()
            if not ip_text:
                skipped += 1
                continue

            try:
                parsed_ip = ipaddress.ip_address(ip_text)
            except ValueError:
                failed += 1
                continue

            if not parsed_ip.is_global:
                smartnode.update(
                    {
                        "latitude": None,
                        "longitude": None,
                        "accuracy_radius_km": None,
                        "time_zone": "",
                    }
                )
                skipped += 1
                continue

            if ip_text not in cache:
                enriched = lookup_city(city_reader, ip_text)
                enriched.update(lookup_asn(asn_reader, ip_text))
                cache[ip_text] = enriched

            enriched = cache[ip_text]
            smartnode.update(enriched)

            latitude = enriched.get("latitude")
            longitude = enriched.get("longitude")
            country_code = str(enriched.get("country_code") or "").upper()

            if latitude is not None and longitude is not None:
                geolocated += 1
                if country_code:
                    country_codes.add(country_code)
            else:
                failed += 1

        summary = report.setdefault("summary", {})
        if isinstance(summary, dict):
            summary["geolocated"] = geolocated
            summary["geolocation_failed"] = failed
            summary["geolocation_skipped"] = skipped
            summary["countries"] = len(country_codes)

        report["geoip"] = {
            "enabled": True,
            "city_database": arguments.geoip_city_db.name,
            "asn_database": (
                arguments.geoip_asn_db.name
                if arguments.geoip_asn_db
                else None
            ),
            "unique_ips_looked_up": len(cache),
            "geolocated": geolocated,
            "failed": failed,
            "skipped": skipped,
            "countries": len(country_codes),
            "location_notice": (
                "Locations are approximate and identify the network or hosting "
                "region associated with an IP address, not an operator's "
                "physical location."
            ),
        }

        destination = arguments.output or arguments.json
        write_json_atomically(report, destination)

        print(f"Report written       : {destination}")
        print(f"Smartnodes processed : {len(report['smartnodes'])}")
        print(f"Unique IPs looked up : {len(cache)}")
        print(f"Geolocated           : {geolocated}")
        print(f"Failed               : {failed}")
        print(f"Skipped              : {skipped}")
        print(f"Countries            : {len(country_codes)}")
        return 0
    except Exception as exc:
        print(f"Error: GeoIP enrichment failed: {exc}", file=sys.stderr)
        return 1
    finally:
        if city_reader is not None:
            city_reader.close()
        if asn_reader is not None:
            asn_reader.close()


if __name__ == "__main__":
    sys.exit(main())
